# Library load, data import and cleaning
# Most participant data is stores in .csv files which have been generated by 
# Gorilla

##libraries, etc

# check required libraries are installed
requires  <-  c("readxl", 
                "data.table", 
                "afex",
                "emmeans",
                "cowplot",
                "tidyverse",
                "bayestestR",
                "BayesFactor",
                "janitor")

# installs required libraries (which aren't already installed)
installs  <-  requires[!requires %in% installed.packages()[,"Package"]]

# load required packages
for (l in requires) require(l, character.only=TRUE)


#participant demographics
setwd("demographics/ppt")
files <-  list.files(pattern="*a.csv")
# First apply read.csv, then rbind
demo <-  do.call(rbind, lapply(files, function(x) read.csv(x, stringsAsFactors = FALSE)))
head(demo,n=1)
colnames(demo)[1] <- "Event.Index" # rename first column to "Event.Index"
demo <- demo[demo$Event.Index != "END OF FILE",]
# remove "begin q" rows
demo <- demo[demo$Question.Key != "BEGIN QUESTIONNAIRE",]
### keep just the relevant columns
demo <- demo[,c("Participant.Private.ID","Question.Key", "Response",'Experiment.Version')]
#long to wide
demo <- demo %>%
  spread(Question.Key, Response)

#study data (mouse version or trackpad. All ppts did buttons too)

#Study information (i.e. mouse)
setwd("../study")
files = list.files(pattern="*.csv")
# First apply read.csv, then rbind
study = do.call(rbind, lapply(files, function(x) read.csv(x, stringsAsFactors = FALSE)))
### keep just the relevant columns
head(study)
colnames(study)[1] <- "Event.Index" # rename first column to "Event.Index"
study<-study[study$Event.Index!="END OF FILE",]
study<-study[study$Question.Key!="BEGIN QUESTIONNAIRE",]
study <- study[,c("Participant.Private.ID","Question.Key", "Response",'Experiment.Version')]
#long to wide
study <- study %>%
  spread(Question.Key, Response)
table(study$mouse) #30 used mouse

# Language information

#Language information
setwd("../Language1")
files = list.files(pattern="*.csv")
# First apply read.csv, then rbind
Language1 = do.call(rbind, lapply(files, function(x) read.csv(x, stringsAsFactors = FALSE)))
head(Language1, n=1)
colnames(Language1)[1] <- "Event.Index" # rename first column to "Event.Index"
### keep just the relevant columns
Language1<-Language1[Language1$Question.Key!="BEGIN QUESTIONNAIRE",]
Language1<-Language1[Language1$Event.Index!="END OF FILE",]
Language1 <- Language1[,c("Participant.Private.ID","Question.Key", "Response",'Experiment.Version')]
#long to wide
Language1 <- Language1 %>%
  spread(Question.Key, Response)
setwd("../Language2")

files = list.files(pattern="*.csv")
# First apply read.csv, then rbind
Language2 = do.call(rbind, lapply(files, function(x) read.csv(x, stringsAsFactors = FALSE)))
### keep just the relevant columns
head(Language2)
colnames(Language2)[1] <- "Event.Index" # rename first column to "Event.Index"
Language2<-Language2[Language2$Question.Key!="BEGIN QUESTIONNAIRE",]
Language2<-Language2[Language2$Event.Index!="END OF FILE",]
Language2 <- Language2[,c("Participant.Private.ID","Question.Key", "Response",'Experiment.Version')]
#long to wide
Language2 <- Language2 %>%
  spread(Question.Key, Response)
head(Language2,n=1)
Language2$`age bilingual-quantised`[is.na(Language2$`age bilingual-quantised`)] <- 1
Language2$bilingual<-ifelse(Language2$`age bilingual-quantised`==1,0,1)
bilingual<-Language2[,c("Participant.Private.ID","bilingual")]
table(bilingual$bilingual) 

# set working directory back to main project working directory
setwd("~/CSE-rep-git")

# load pilot data (don't run if you don't want pilot data)
setwd("~/CSE-rep-git/pilot")
files = list.files(pattern="38sw")
pilot= do.call(rbind, lapply(files, function(x) read.csv(x, stringsAsFactors = FALSE)))
pilot$lang<-"bilingual"
colnames(pilot)[1] <- "Event.Index" # rename first column to "Event.Index"

# load monolingual data
setwd("~/CSE-rep-git/not\ MT/monolingual")
files = list.files(pattern="38sw")
mono= do.call(rbind, lapply(files, function(x) read.csv(x, stringsAsFactors = FALSE)))
mono$lang<-"monolingual"
colnames(mono)[1] <- "Event.Index" # rename first column to "Event.Index"

# load bilingual data
setwd("~/CSE-rep-git/not\ MT/November")

files = list.files(pattern="38sw")
Nov = do.call(rbind, lapply(files, function(x) read.csv(x, stringsAsFactors = FALSE)))
Nov$lang<-"bilingual"
colnames(Nov)[1] <- "Event.Index" # rename first column to "Event.Index"

# combine and clean data
setwd("~/CSE-rep-git")



# analyse data

setwd("new_analysis")



#bilingual data CSE in flanker task:

rt_density_plot <- ggplot(data = alldata) +
  geom_density(mapping = aes(mapping = aes(x=RT, group=interaction))